---
title: "Surrogates_AFM_revision"
author: "Jinshi"
date: "5/21/2020"
output: html_document
---



```{r, fig.width=8, fig.height=6}
# plot the hypothesis diagram
dat <- tibble(soilT = seq(-20, 20, 1), Rs = seq(0, 20, 0.5))

diag_hypo <- function(sdata, slo_air, slo_soil, intcp, var_text, var_col){
  sdata %>% 
    ggplot(aes(soilT, Rs)) +
    geom_point(col = "white") +
    geom_abline(slope = slo_air, intercept = intcp, size = 1.05,
                linetype = "dashed", col = var_col) +
    geom_abline(slope = slo_soil, intercept = intcp, size = 1.05,
                linetype = "solid", col = var_col) +
    labs(y=expression(R[S]~(g~C~m^{-2}~{day}^{-1}))) +
    theme(axis.title.x = element_blank()) +
    annotate(geom="text", x=-12.5, y=19, label=var_text, size = 5)
}

diag_hypo1 <- function(sdata, slo_air, slo_soil, intcp, var_text, var_col){
  sdata %>% 
    ggplot(aes(soilT, Rs)) +
    geom_point(col = "white") +
    geom_abline(slope = slo_air, intercept = intcp, size = 1.05,
                linetype = "dashed", col = var_col) +
    geom_abline(slope = slo_soil, intercept = intcp, size = 1.05,
                linetype = "solid", col = var_col) +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank()) +
    annotate(geom="text", x=-12.5, y=19, label=var_text, size = 5)
}

diag_hypo2 <- function(sdata, slo_air, slo_soil, intcp, var_text){
  sdata %>% 
    ggplot(aes(soilT, Rs)) +
    geom_point(col = "white") +
    geom_abline(slope = slo_air, intercept = intcp, size = 1.05,
                linetype = "dashed", col = "black") +
    geom_abline(slope = slo_soil, intercept = intcp, size = 1.05,
                linetype = "solid", col = "black") +
    labs(y=expression(R[S]~(g~C~m^{-2}~{day}^{-1})),
         x = paste("Tsoil or Tair\n", "SWC or Pm")
         ) +
    annotate(geom="text", x=-12.5, y=19, label=var_text, size = 5)
}

diag_hypo3 <- function(sdata, slo_air, slo_soil, intcp, var_text, var_col){
  sdata %>% 
    ggplot(aes(soilT, Rs)) +
    geom_point(col = "white") +
    geom_abline(slope = slo_air, intercept = intcp, size = 1.05,
                linetype = "dashed", col = var_col) +
    geom_abline(slope = slo_soil, intercept = intcp, size = 1.05,
                linetype = "solid", col = var_col) +
    labs(x = paste("Tair\n", "Pm")) +
    theme(axis.title.y = element_blank()) +
    annotate(geom="text", x=-12.5, y=19, label=var_text, size = 5)
}

plot_grid(
  diag_hypo(dat, 0.405, 0.505, 10, "+/+", "black"),
  diag_hypo1(dat, -0.0, 0.505, 10, "+/na", "black"),
  diag_hypo1(dat, -0.505, 0.505, 10, "+/-", "black"),
  
  diag_hypo(dat, -0.05, 0.0, 10, "na/na", "black"),
  diag_hypo1(dat, 0.505, 0.0, 10, "na/+", "black"),
  diag_hypo1(dat, -0.505, 0.0, 10, "na/-", "black"),
  
  diag_hypo2(dat, -0.505, -0.405, 10, "-/-"),
  diag_hypo3(dat, -0.0, -0.405, 10, "-/na", "black"),
  diag_hypo3(dat, 0.505, -0.405, 10, "-/+", "black"),
  
  ncol = 3,
  rel_widths = c(1.1,1,1), rel_heights = c(1,1,1.135)
)


ggsave("outputs_revision/Figure2.jpg", width = 8, height = 8, dpi = 300, units = "in")
```



```{r}
t_results %>% 
  select(Study_number, SiteID,
         p_b, p_Tm_b,  first_b, first_Tm_b,
         # first_R2, first_Tm_R2,
         # p_TsTair_b, TsTair_R2,
         # Biome_group, Ecosystem_group, Leaf_group, Drainage_group,
         MAT, MAP) %>% 
  mutate(
    Surrogate_group = case_when(
    p_b < 0.05 & first_b > 0 & p_Tm_b < 0.05 & first_Tm_b > 0 ~ "Yes (78.75%)",
    p_b < 0.05 & first_b > 0 & p_Tm_b >= 0.05 ~ "No (7.61%)",
    p_b < 0.05 & first_b > 0 & p_Tm_b < 0.05 & first_Tm_b < 0 ~ "No (7.61%)",
    
    p_b >= 0.05 & p_Tm_b >= 0.05 ~ "NCR (13.64%)",
    p_b >= 0.05 & p_Tm_b < 0.05 & first_Tm_b > 0 ~ "No (7.61%)",
    p_b >= 0.05 & p_Tm_b < 0.05 & first_Tm_b < 0 ~ "No (7.61%)",
    
    p_b < 0.05 & first_b < 0 & p_Tm_b < 0.05 & first_Tm_b < 0 ~ "Yes (78.75%)",
    p_b < 0.05 & first_b < 0 & p_Tm_b >= 0.05 ~ "No (7.61%)",
    p_b < 0.05 & first_b < 0 & p_Tm_b < 0.05 & first_Tm_b > 0 ~ "No (7.61%)",
    TRUE ~ "Other"),
    
    SLR_group = case_when(
    p_b < 0.05 & first_b > 0 & p_Tm_b < 0.05 & first_Tm_b > 0 ~ "p-p",
    p_b < 0.05 & first_b > 0 & p_Tm_b >= 0.05 ~ "p-o",
    p_b < 0.05 & first_b > 0 & p_Tm_b < 0.05 & first_Tm_b < 0 ~ "p-n",
    
    p_b >= 0.05 & p_Tm_b >= 0.05 ~ "o-o",
    p_b >= 0.05 & p_Tm_b < 0.05 & first_Tm_b > 0 ~ "o-p",
    p_b >= 0.05 & p_Tm_b < 0.05 & first_Tm_b < 0 ~ "o-n",
    
    p_b < 0.05 & first_b < 0 & p_Tm_b < 0.05 & first_Tm_b < 0 ~ "n-n",
    p_b < 0.05 & first_b < 0 & p_Tm_b >= 0.05 ~ "n-o",
    p_b < 0.05 & first_b < 0 & p_Tm_b < 0.05 & first_Tm_b > 0 ~ "n-p",
    
    TRUE ~ "Other")) %>% 
  na.omit() ->
  t_results_group

t_results_group %>% 
  select(SLR_group) %>% 
  group_by(SLR_group) %>% 
  tally() %>% 
  mutate(perc = n/880*100)

t_results_group %>% 
  select(Surrogate_group) %>% 
  count()

t_results_group %>% 
  filter(SLR_group %in% c("a-g", "b-h", "c-f"))

```


```{r}
swc_results %>% 
  select(Study_number, SiteID, p_b, p_pm_b, first_b, first_pm_b) %>% 
  mutate(
    Surrogate_group = case_when(
    p_b < 0.05 & first_b > 0 & p_pm_b < 0.05 & first_pm_b > 0 ~ "Yes (14.79%)",
    p_b < 0.05 & first_b > 0 & p_pm_b >= 0.05 ~ "No (46.75%)",
    p_b < 0.05 & first_b > 0 & p_pm_b < 0.05 & first_pm_b < 0 ~ "No (46.75%)",
    
    p_b >= 0.05 & p_pm_b >= 0.05 ~ "NCR (38.46%)",
    p_b >= 0.05 & p_pm_b < 0.05 & first_pm_b > 0 ~ "No (46.75%)",
    p_b >= 0.05 & p_pm_b < 0.05 & first_pm_b < 0 ~ "No (46.75%)",
    
    p_b < 0.05 & first_b < 0 & p_pm_b < 0.05 & first_pm_b < 0 ~ "Yes (14.79%)",
    p_b < 0.05 & first_b < 0 & p_pm_b >= 0.05 ~ "No (46.75%)",
    p_b < 0.05 & first_b < 0 & p_pm_b < 0.05 & first_pm_b > 0 ~ "No (46.75%)",
    TRUE ~ "Other"),
    
    SLR_group = case_when(
    p_b < 0.05 & first_b > 0 & p_pm_b < 0.05 & first_pm_b > 0 ~ "p-p",
    p_b < 0.05 & first_b > 0 & p_pm_b >= 0.05 ~ "p-o",
    p_b < 0.05 & first_b > 0 & p_pm_b < 0.05 & first_pm_b < 0 ~ "p-n",
    
    p_b >= 0.05 & p_pm_b >= 0.05 ~ "o-o",
    p_b >= 0.05 & p_pm_b < 0.05 & first_pm_b > 0 ~ "o-p",
    p_b >= 0.05 & p_pm_b < 0.05 & first_pm_b < 0 ~ "o-n",
    
    p_b < 0.05 & first_b < 0 & p_pm_b < 0.05 & first_pm_b < 0 ~ "n-n",
    p_b < 0.05 & first_b < 0 & p_pm_b >= 0.05 ~ "n-o",
    p_b < 0.05 & first_b < 0 & p_pm_b < 0.05 & first_pm_b > 0 ~ "n-p",
    TRUE ~ "Other")
    ) ->
  swc_results_group

swc_results_group %>% 
  select(SLR_group) %>% 
  group_by(SLR_group) %>% 
  tally() %>% 
  mutate(perc = n/507*100)
```



```{r}
t_results_group %>% 
  select(Surrogate_group) %>% 
  count() %>% 
  mutate(percent = freq/nrow(t_results_group)*100) ->
  t_surrogate_perc

swc_results_group %>% 
  select(Surrogate_group) %>% 
  count() %>% 
  mutate(percent = freq/nrow(swc_results_group)*100) ->
  swc_surrogate_perc

var_perc <- c(paste0(round(swc_surrogate_perc$percent,2),"%"),
              paste0(round(t_surrogate_perc$percent,2),"%"))

plot_grid(
  t_results_group %>% 
    arrange(Surrogate_group) %>% 
    ggplot(aes(Surrogate_group, fill = SLR_group)) +
    geom_bar(stat = "count", width = 0.75) +
    labs(x = expression(Temperature~surrogates),
         y = expression(Count)) +
    annotate("text", x = c(1:3), y = c(150, 100, 650), label = paste0(round(t_surrogate_perc$percent,2),"%")) +
    theme(legend.title = element_blank()),

  swc_results_group %>% 
    arrange(Surrogate_group) %>%
    ggplot(aes(Surrogate_group, fill = SLR_group)) +
    geom_bar(stat = "count", width = 0.75) +
    labs(x = expression(Moisture~surrogates)) +
    annotate("text", x = c(1:3), y = c(210, 250, 85), label = paste0(round(swc_surrogate_perc$percent,2),"%")) +
    theme(legend.position = "none",
          axis.title.y = element_blank()),
  
  rel_widths = c(1.25, 1)
)

bind_rows(
  t_results_group %>% 
  select(Surrogate_group, SLR_group) %>% 
  mutate(Surrogate = "(a) Temperature surrogates"),
  
  swc_results_group %>% 
  select(Surrogate_group, SLR_group) %>% 
  mutate(Surrogate = "(b) Moisture surrogates")
  ) %>% 
  ggplot(aes(Surrogate_group, fill = SLR_group)) +
  geom_bar(stat = "count", width = 0.75) +
  facet_grid(cols = vars(Surrogate), scales = "free") +
  labs(y = expression(Count)) +
  scale_fill_manual(values = c("lightslateblue", "darkorange", "darkorange3", "hotpink3", "gray", "hotpink", 
                               "firebrick", "red", "blue")) +
  # annotate("text", x = c(1:6), y = c(210, 250, 85, 210, 250, 85), label = var_perc) +
  theme(legend.title = element_blank(),
        axis.title.x = element_blank()) 

# ggsave("outputs_revision/Figure_surrogates_summary.jpg", width = 7, height = 4, dpi = 300, units = "in")
```

